---
- debug:
    msg: "{{ vars[(role_path | basename).split('.')[-1].replace('-','_')] }}"
  when: DEBUG | d() | bool

- include_tasks: prepare.yml
- include_tasks: configure.yml
- include_tasks: install.yml